import { cp, readFile, readdir, rm, writeFile } from "node:fs/promises";

const root = new URL("../", import.meta.url);
const dist = new URL("../dist/", import.meta.url);

await rm(new URL("assets/", root), { recursive: true, force: true });
await cp(new URL("assets/", dist), new URL("assets/", root), { recursive: true });
await cp(new URL("favicon.svg", dist), new URL("favicon.svg", root));

const html = await readFile(new URL("index.html", dist), "utf8");
await writeFile(
  new URL("index.html", root),
  `${html}\n<!-- Generated by npm run build:pages; edit src/index.html instead. -->\n`,
);
await writeFile(new URL(".nojekyll", root), "");

const assets = await readdir(new URL("assets/", root));
console.log(`Synchronized GitHub Pages fallback (${assets.length} assets).`);
